BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `User` (
	`UserID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FirstName`	TEXT NOT NULL,
	`LastName`	TEXT NOT NULL,
	`UserType`	INTEGER
);
CREATE TABLE IF NOT EXISTS `Student` (
	`Student_MatricID`	TEXT UNIQUE,
	`UserID`	INTEGER NOT NULL,
	`DepartmentID`	INTEGER NOT NULL,
	`Level`	INTEGER,
	FOREIGN KEY(`UserID`) REFERENCES `User`(`UserID`) ON DELETE SET NULL,
	PRIMARY KEY(`Student_MatricID`),
	FOREIGN KEY(`DepartmentID`) REFERENCES `Department`(`DepartmentID`) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS `Faculty` (
	`FacultyID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FacultyName`	TEXT
);
CREATE TABLE IF NOT EXISTS `Department` (
	`DepartmentID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FacultyID`	INTEGER,
	`DepartmentName`	TEXT,
	`ProgrammeSpan`	INTEGER,
	FOREIGN KEY(`FacultyID`) REFERENCES `Faculty`(`FacultyID`) ON DELETE SET NULL
);
COMMIT;
